print()
print("    *    "*2)
print("   * *   "*2)
print("  *   *  "*2)
print(" *     * "*2)
print("***   ***"*2)
print("  *   *  "*2)
print("  *   *  "*2)
print("  *****  "*2)

print()
print(" "*4,  "*"," "*4, sep='', end='|\n')
print(" "*3, "* *"," "*3, sep='', end='|\n')
print(" "*2,"*   *"," "*2, sep='', end='|\n')
print(" ", "*     *"," ", sep='', end='|\n')
print("***   ***", sep='', end='|\n')
print(" "*3,"*"," "*1,"*"," "*3, sep='', end='|\n')
print(" "*3,"*"," "*1,"*"," "*3, sep='', end='|\n')
print(" "*3,"*"," "*1,"*"," "*3, sep='', end='|\n')
print(" "*3,"*"*3," "*3, sep='', end='|\n')

print("Hello\nWorld")
print('Hello\\nWorld')
